[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 100


[tool.isort]
profile = "black"


[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]


[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]
