apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-service-account
  namespace: rag-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rag-system
  name: rag-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rag-role-binding
  namespace: rag-system
subjects:
- kind: ServiceAccount
  name: rag-service-account
  namespace: rag-system
roleRef:
  kind: Role
  name: rag-role
  apiGroup: rbac.authorization.k8s.io
